# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task3

  # Utils

  pod 'SwiftLint'

  # Data

  pod 'ObjectMapper', '~> 3.5'

end
